<a href="https://colab.research.google.com/github/SomyaH99/python-personal-/blob/main/python_pratice'.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

practise workbook

different data types in python:
1. numeric
2. string
3. boolean
4. datetime

Indentation in Python:
Indentation refers to the spaces at the beginning of a code line.


In [ ]:
# example of indentation
if 5>2:
  print('Five is greater than 2')

Five is greater than 2


Python variable:
Variable are containers for storing data values. A variable is created the moment you first assign a value to it.

* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
* Variable names are case-sensitive (age, Age and AGE are three different variables)

Python Variables - Assign Multiple Values

Many Values to Multiple Variables
Python allows you to assign values to multiple variables in one line:

In [ ]:
x, y,z = 'orange', 'banana', 'cherry'
print(x)
print(y)
print(z)

orange
banana
cherry


One Value to Multiple Variables
* And you can assign the same value to multiple variables in one line:

In [ ]:
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange


Unpack a Collection

if you have values in lists, tuples etc python allows you to extract the values into variables. this is called unpackng in python


In [ ]:
fruits= ['apple','banana', 'orage']
x,y,z = fruits
print(x)
print(y)
print(z)

apple
banana
orage


output variables 


In [ ]:
x = 5
y = "John"
print(x, y)

5 John


Global Variables
Variables that are created outside of a function are known as global variables.
Global variables can be used by everyone, both inside of functions and outside.

Strings slicing.


Strings in python are surrounded by either single quotation marks, or double quotation marks.

Slice From the Start

By leaving out the start index, the range will start at the first character:

In [ ]:
b = "Hello, World!"
print(b[:5])

Hello


By leaving out the end index, the range will go to the end:

In [ ]:
b = "Hello, World!"
print(b[2:])

llo, World!


Negative Indexing
Use negative indexes to start the slice from the end of the string:

In [ ]:
b = "Hello, World!"
print(b[-5:-2])

orl


Upper Case

Lower Case

Remove Whitespace

In [ ]:
a = "Hello, World!"
print(a.upper())

HELLO, WORLD!


In [ ]:
a = "Hello, World!"
print(a.lower())

hello, world!


In [ ]:
a = " Hello, World! "
print(a.strip())

Hello, World!


Remove Whitespace

The strip() method removes any whitespace from the beginning or the end:

In [ ]:
a = " Hello,    World! "
print(a.strip()) 

Hello,    World!


Replace String

The replace() method replaces a string with another string:

In [ ]:
a = "Hello, World!"
print(a.replace("H", "J"))

Jello, World!


Split String

The split() method returns a list where the text between the specified separator becomes the list items.

In [ ]:
a = "Hello, World!"
print(a.split(",")) 

['Hello', ' World!']


String Concatenation

To concatenate, or combine, two strings you can use the + operator.

In [ ]:
a = "Hello"
b = "World"
c = a + b
print(c)

HelloWorld


To add a space between them, add a " ":

In [ ]:
a = "Hello"
b = "World"
c = a + " " + b
print(c)

Hello World


String Format

The format() method takes the passed arguments, formats them, and places them in the string where the placeholders {} are:


In [ ]:
age = 36
text = "my name is somya, and I am {}"
print(text.format(age))

my name is somya, and I am 36


In [ ]:
quantity = 3
item = 567
price = 49.95
myorder = "i want {} pieces of item {} for {} dollars."
print(myorder.format(quantity,item,price))

i want 3 pieces of item 567 for 49.95 dollars.


In [ ]:
a = 10 
b=20 
c = 30

In [ ]:
if a>b:
  print("B is greater than a")

In [ ]:
if a>b:
  print("a is greater than b")
else:
  print('b is greater than a ')

b is greater than a 


a = 10
b=20
c = 30


In [ ]:
if (a>b) & (a>c):
  print("A is greatest")
elif (b>a) & (b>c):
  print('b is greatest')
else:
  print('c is the greatest')

c is the greatest


In [ ]:
tup1 = ('a','b', 'c')

In [ ]:
if 'z' in tup1:
  print("value a is present in tup1")
else:
  print("value z is not present")


In [ ]:
i = 1
while i<=10:
  print(i)
  i = i + 1

In [ ]:
i=1
n=2
while i<=10:
  print(n, "*", i, "=", n*i)
  i = i+1

In [ ]:
l1 = ['mango', 'apple', 'grapes', 'orange']

In [ ]:
for i in l1:
  print(i)

In [ ]:
l1 = ['orange', 'black', 'white']
l2 = ['chair', 'book','laptop']

In [ ]:
for i in l1:
  for j in l2:
    print(i,j)

Functions;

In [ ]:
def hello():
  print("hello world")

In [ ]:
hello()

hello world


In [ ]:
def add_10(x):
  return x+10

In [ ]:
add_10(5)

15

In [ ]:
def odd_even(x):
  if x%2==0:
    print(x,"is even")
  else:
    print(x,"is odd")

In [ ]:
odd_even(10)

10 is even


In [ ]:
g= lambda x : x*x*x

In [ ]:
g(10)

1000

LAMBDA WITH FILTER

In [ ]:
l1 =[23,34,56,78,89,90,34,56,54,76,87,98,99]

In [ ]:
final_list = list(filter(lambda x: (x%2==0), l1)) 

In [ ]:
final_list

[34, 56, 78, 90, 34, 56, 54, 76, 98]

map

In [ ]:
l1 = [1,2,3,4,5,6,7,8]

In [ ]:
new = list(map(lambda x : x*2, l1))

In [ ]:
new

[2, 4, 6, 8, 10, 12, 14, 16]

In [ ]:
from functools import reduce

In [ ]:
sum= reduce(lambda x ,y: x+y ,l1)

In [ ]:
sum

36

In [ ]:
class Phone:
  def make_call(self):
    print('I am makin a call')
  def play_game(self):
    print('I am playin a game')

In [ ]:
p1 = Phone()

In [ ]:
p1.make_call()

I am makin a call


In [ ]:
p1.play_game()

I am playin a game


In [1]:
import numpy as np

In [2]:
l1 = [1,2,3,4]

In [3]:
n1 =np.array(l1)

In [4]:
type(n1)

numpy.ndarray

In [5]:
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [6]:
type(n2)

numpy.ndarray

In [7]:
n3 = np.zeros((10,10))

In [8]:
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
type(n3)

numpy.ndarray

In [10]:
n4 = np.full((3,3), 10)

In [11]:
n4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [12]:
n1 = np.arange(50,101)

In [13]:
n1

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
n1 = np.arange(50,510,10)

In [15]:
n1

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490, 500])

In [16]:
np.random.randint(1,10000,10)

array([  81,   60, 3936, 6254, 4204, 3858, 7550, 9585, 4490, 3950])

In [17]:
n1 = np.array([[1,2,3,4],[4,3,2,1]])